using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Depra.CodeGen.Attributes;
using Depra.CodeGen.Context;
using Depra.CodeGen.Core;
using Leopotam.EcsLite.Baking.Runtime.Components;

namespace Leopotam.EcsLite.Baking.CodeGen.Editor
{
	[Generator]
	[SuppressMessage("ReSharper", "ClassNeverInstantiated.Global")]
	public sealed class AuthoringComponentGenerator : ICodeGenerator
	{
		void ICodeGenerator.Execute(GeneratorContext context)
		{
			var componentTypes = AppDomain.CurrentDomain
				.GetAssemblies()
				.SelectMany(assembly => assembly.GetTypes())
				.Where(type => type.IsValueType && Attribute.IsDefined(type, typeof(BakeAttribute)));

			foreach (var componentType in componentTypes)
			{
				var className = $"{componentType.Name}{nameof(AuthoringComponent)}";
				var code = @$"//<auto-generated/>
using Depra.Ecs.Baking.Runtime.Components;

public sealed class {className} : {nameof(AuthoringComponent)}<{componentType.FullName}> {{ }}";

				context.AddCode($"{nameof(AuthoringComponent)}s/{className}.cs", code);
			}
		}
	}
}