// SPDX-License-Identifier: Apache-2.0
// © 2023 Nikolay Melnikov <n.melnikov@depra.org>

using System;
using System.Linq;
using Depra.CodeGen.Attributes;
using Depra.CodeGen.Context;
using Depra.CodeGen.Core;

namespace Leopotam.EcsLite.Baking.CodeGen.Editor
{
	[Generator]
	public sealed class AuthoringComponentGenerator : ICodeGenerator
	{
		void ICodeGenerator.Execute(GeneratorContext context)
		{
			var componentTypes = AppDomain.CurrentDomain
				.GetAssemblies()
				.SelectMany(assembly => assembly.GetTypes())
				.Where(type => type.IsValueType && Attribute.IsDefined(type, typeof(DefaultBaking)));

			foreach (var componentType in componentTypes)
			{
				var className = $"{componentType.Name}AuthoringComponent";
				var code = @$"//<auto-generated/>
using Leopotam.EcsLite.Baking.Runtime.Components;

public sealed class {className} : AuthoringComponent<{componentType.FullName}> {{ }}";

				context.AddCode($"AuthoringComponents/{className}.cs", code);
			}
		}
	}
}